### ISSUE TITLE
Document ways of using markscribe with gitlab & heptapod 

### ISSUE THREAD

**Issue by arthurlogilab** [muesli/markscribe#20]
I've been happy to use markscribe with readme-scribe on github with github actions, but wanted to have it working too on gitlab or heptapod (friendly fork of gitlab with mercurial support). 

Here is the `.gitlab-ci.yml` I'm using : 

```
generate-readme:
  image: fribbledom/markscribe
  script:
    - mkdir output
    - /go/bin/markscribe -write output/README.md README.md.tpl
  artifacts:
    paths:
      - output/
commit-readme:
  image: logilab/mercurial
  script:
    - mv output/README.md .
    - hg add README.md
    - 'hg commit -m "build: 🤖 generated README.md [skip ci]"'
    - hg push https://$GITLAB_USER_LOGIN:$PERSONAL_ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH
```

There's probably an easy way to do the autocommit with git for gitlab...
